import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/generics/Navbar";
import Providers from "@/components/generics/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* Head content like meta tags, title, and links to CSS */}</head>
      <body className={inter.className}>
        <Providers>
          <header>
            <Navbar />
          </header>
          {children}
          {/* Other body content */}
        </Providers>
      </body>
    </html>
  );
}
